runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT app:app


handlers:
- url: /static
  static_dir: static

- url: /.*
  script: app.app

runtime_config:
  python_version: 3

readiness_check:
  path: "/health"

liveness_check:
  path: "/health"